export class VehicleOnline {
  public vehicleId: number;
  public vehiclePlate: string;
  public latitude: number;
  public longitude: number;
  public state: number;
  public velocity: number;
  public gpsTime: Date;
  public vehicleTime: Date;
  public iconCode: number;
  public privateCode: string;
  public dataExt: number;
  public direction: number;
  public stopTime: number;
  public lastTimeMove: Date;
  public velocityMechanical: number;
  public isLocked: boolean;
  public isShow: boolean;
  public flags: number;
  public xnCode: number;
  constructor(data: any) {
    this.vehicleId = data[0];
    this.vehiclePlate = data[1];
    this.latitude = data[2];
    this.longitude = data[3];
    this.state = data[4];
    this.velocity = data[5];
    this.gpsTime = data[6];
    this.vehicleTime = data[7];
    this.iconCode = data[8];
    this.privateCode = data[9];
    this.lastTimeMove = data[10];
    this.velocityMechanical = data[11];
    this.isLocked = data[12];
    this.isShow = data[13];
    this.flags = data[14];
    this.dataExt = data[15];
    this.direction = data[16];
    this.xnCode = data[17];
    this.stopTime = data[18];
  }
}
